const AFF_CATS = ["Aşk", "Bolluk ve Para", "Şükür", "Özgüven", "Sağlık", "Huzur", "Başarı"];
const CAT_COLORS = { "Aşk": "#C0567D", "Bolluk ve Para": "#B9781F", "Şükür": "#5E8A6A", "Özgüven": "#8459AE", "Sağlık": "#3F84A0", "Huzur": "#6A6FB0", "Başarı": "#5B2E4F" };
const AFF = {
  "Aşk": [
    "Sevgiye layık biriyim.",
    "Kalbim sevgiyi vermeye ve almaya açık.",
    "Hayatımda sevgi dolu ilişkiler büyüyor.",
    "Önce kendimi seviyorum, sevgi bana kolayca geliyor.",
    "Beni olduğum gibi seven insanlarla çevriliyim.",
    "Sevgiyi korkusuzca ifade ediyorum.",
    "İlişkilerimde saygı ve güven var.",
    "Kalbimi iyileştiriyor ve yeniden açıyorum.",
    "Sevildiğimi hissetmeye kendime izin veriyorum.",
    "Bana iyi gelen sevgiyi hayatıma çekiyorum.",
    "Sevdiklerimle aramdaki bağ her gün güçleniyor.",
    "Sevgi benim doğal halim.",
    "Kendime şefkatle bakıyorum.",
    "Eski kırgınlıkları bırakıyor, sevgiye yer açıyorum.",
    "Aşk hayatıma doğru zamanda geliyor.",
    "Sınırlarımı koruyarak sevebiliyorum.",
    "Sevgiyi hak etmek için değişmem gerekmiyor.",
    "Her gün kendimle daha barışığım.",
    "Kalbimdeki sevgi etrafıma yayılıyor.",
    "İçten ve dürüst ilişkiler kuruyorum.",
    "Sevmek de sevilmek de benim için güvenli.",
    "Kendimi sevdikçe dünya da bana sevgiyle dönüyor.",
    "Bana değer veren insanları fark ediyorum.",
    "İlişkilerimde anlaşılmış ve dinlenmiş hissediyorum.",
    "Sevgimi küçük jestlerle gösteriyorum.",
    "Ailemle ve dostlarımla sevgi dolu anlar yaşıyorum.",
    "Kalbim yumuşak ama güçlü.",
    "Kendime âşık olmayı öğreniyorum.",
    "Geçmişin yükü olmadan seviyorum.",
    "Doğru insan beni olduğum gibi kabul ediyor.",
    "Sevgi bende eksik değil, bolca var.",
    "Affetmek kalbimi özgürleştiriyor.",
    "Yakın olmaktan korkmuyorum.",
    "Sevgiyi kıyaslamadan, beklentisiz veriyorum.",
    "Her ilişki bana yeni bir şey öğretiyor.",
    "Kendi değerimi biliyor, seçimlerimi buna göre yapıyorum.",
    "Sıcaklık ve şefkat hayatımın merkezinde.",
    "Sevgi dolu sözler söylüyor, sevgi dolu sözler duyuyorum.",
    "Kalbimin sesini dinliyorum.",
    "Yalnız olduğumda da tamım.",
    "Sevgi her gün beni yeniden buluyor.",
    "İlişkilerim beni büyütüyor.",
    "Kendime gösterdiğim nezaket başkalarına da yansıyor.",
    "Mutlu bir ilişkiyi hak ediyorum.",
    "Sevgiyi kabul etmekte zorlanmıyorum.",
    "Sevdiğim insanlara zaman ayırıyorum.",
    "Kalbim hem cesur hem nazik.",
    "Aşk benim için huzur demek.",
    "Bugün birine sevgimi söyleyeceğim.",
    "Birlikte gülmek, birlikte büyümek bana iyi geliyor.",
    "Sevginin her türlüsüne açığım.",
    "Kendimi sevdiğim her gün daha çok parlıyorum.",
    "Sevgi dolu bir hayat kuruyorum."
  ],
  "Bolluk ve Para": [
    "Para bana kolaylıkla ve bolca geliyor.",
    "Bolluğu hak ediyorum.",
    "Emeklerimin karşılığını fazlasıyla alıyorum.",
    "Parayla sağlıklı ve huzurlu bir ilişkim var.",
    "Gelirim her geçen gün artıyor.",
    "Paramı bilinçli ve akıllıca yönetiyorum.",
    "Yeni gelir kapıları önümde açılıyor.",
    "Bolluk zihniyetiyle düşünüyorum.",
    "Harcadığım her kuruş bana bereketle geri dönüyor.",
    "Finansal özgürlüğe her gün yaklaşıyorum.",
    "Yeteneklerim bana kazanç getiriyor.",
    "Hayatımda her şeyin fazlası var.",
    "Paranın iyi bir enerji olduğuna inanıyorum.",
    "Birikimlerim düzenli olarak büyüyor.",
    "Fırsatları görüyor ve değerlendiriyorum.",
    "Borçlarımdan kurtuluyor, ferahlıyorum.",
    "Cömert olmak bana daha fazlasını getiriyor.",
    "Değerimi biliyor, emeğimin hakkını istiyorum.",
    "Para hayallerimi gerçekleştirmeme yardım ediyor.",
    "Evren bana her gün bolluk gönderiyor.",
    "Kazanmak benim için doğal ve kolay.",
    "Finansal kararlarımı güvenle veriyorum.",
    "Sahip olduklarım için minnettarım, daha fazlası yolda.",
    "Bereket evimde ve hayatımda.",
    "Zenginlik benim için mümkün.",
    "Para konusunda kendimi güvende hissediyorum.",
    "İşimi severek yapıyor, bolca kazanıyorum.",
    "Beklenmedik yerlerden güzel kazançlar geliyor.",
    "Her gün daha bilinçli harcıyorum.",
    "Kıtlık korkularını bırakıyorum.",
    "Bolluğun akışına güveniyorum.",
    "Kendi kazancımı yaratma gücüne sahibim.",
    "Maddi hedeflerime adım adım ulaşıyorum.",
    "Para bana özgürlük ve seçenek sunuyor.",
    "Bugün bolluk için yeni bir adım atıyorum.",
    "Başkalarının başarısına sevinebiliyorum, sıra bana da geliyor.",
    "Bütçem dengede, zihnim rahat.",
    "Hem kazanmayı hem paylaşmayı seviyorum.",
    "Yaratıcılığım bana yeni gelir fikirleri getiriyor.",
    "Para hakkındaki eski inançlarımı yeniliyorum.",
    "Geleceğim için sağlam bir temel kuruyorum.",
    "Her ay biraz daha fazla biriktiriyorum.",
    "İhtiyacım olan her şey bana zamanında geliyor.",
    "Bolluk içinde yaşamak benim hakkım.",
    "Değer kattıkça kazancım artıyor.",
    "Paraya açık ve hazırım.",
    "Maddi konularda sakin ve bilinçliyim.",
    "Bereketli bir yılın içindeyim.",
    "Zenginliğim sadece paramda değil, hayatımın her yerinde.",
    "Yatırımlarım ve emeklerim meyve veriyor.",
    "Kazandıkça daha çok iyilik yapabiliyorum.",
    "Bolluk kapımı çalıyor, kapıyı açıyorum.",
    "Finansal huzur içinde yaşıyorum."
  ],
  "Şükür": [
    "Bugün nefes alabildiğim için şükrediyorum.",
    "Hayatımdaki küçük mucizeleri fark ediyorum.",
    "Sahip olduklarım bana yetiyor.",
    "Sevdiklerim için minnettarım.",
    "Her sabah yeni bir gün için şükrediyorum.",
    "Başımın üstündeki çatı için minnettarım.",
    "Soframa gelen her lokma için şükrediyorum.",
    "Zor günlerin bana öğrettikleri için minnettarım.",
    "Bedenimin benim için yaptığı her şeye teşekkür ediyorum.",
    "Güneşin sıcaklığı için şükrediyorum.",
    "Hayatıma giren güzel insanlar için minnettarım.",
    "Bugün gülümsememe sebep olan şeyleri sayıyorum.",
    "Şükrettikçe hayatım daha da güzelleşiyor.",
    "Geçmişime teşekkür ediyor, bugüne kucak açıyorum.",
    "Sağlığım için minnettarım.",
    "Öğrenebildiğim her şey için şükrediyorum.",
    "Sıradan anların değerini biliyorum.",
    "Bir fincan çayın huzuru için minnettarım.",
    "Dostlarımın varlığı için şükrediyorum.",
    "Bu kadar yol geldiğim için kendime teşekkür ediyorum.",
    "Doğanın güzelliği karşısında minnettarım.",
    "Bugün bana verilen fırsatlar için şükrediyorum.",
    "Kalbim minnetle dolu.",
    "Ailemin sevgisi için minnettarım.",
    "Gülebildiğim her an için şükrediyorum.",
    "Bana yardım eden herkese teşekkür ediyorum.",
    "Yaşadığım her deneyim beni zenginleştiriyor.",
    "Zihnimin berraklığı için minnettarım.",
    "Bugünün sessizliği için şükrediyorum.",
    "Sahip olmadıklarım yerine sahip olduklarıma bakıyorum.",
    "Yağmurun sesi için bile minnettarım.",
    "Uyandığım her sabah bir hediye.",
    "İyiliğe şahit olduğum her an için şükrediyorum.",
    "Hayallerim olduğu için minnettarım.",
    "Güvende olduğum için şükrediyorum.",
    "Bana iyi gelen alışkanlıklarım için minnettarım.",
    "Küçük şeylerle mutlu olabildiğim için şükrediyorum.",
    "Hayatın bana sunduğu ikinci şanslar için minnettarım.",
    "Yıldızlı bir gecenin güzelliği için şükrediyorum.",
    "Okuduğum kitaplar ve öğrendiklerim için minnettarım.",
    "Kendime ayırabildiğim zaman için şükrediyorum.",
    "Kalbimi ısıtan anılar için minnettarım.",
    "Şükür benim için bir yaşam biçimi.",
    "Bugün beni güldüren her şeye teşekkür ediyorum.",
    "Hayatın akışına teşekkür ediyorum.",
    "Bugün de bir şeylere sevinebildiğim için minnettarım.",
    "Bana bir şey öğreten herkese şükrediyorum.",
    "Evimin sıcaklığı için minnettarım.",
    "Beni dinleyen ve anlayan insanlar için şükrediyorum.",
    "Her yeni mevsim için minnettarım.",
    "Zorlukların ardından gelen huzur için şükrediyorum.",
    "Olduğum kişi için minnettarım.",
    "Şimdi, burada olduğum için şükrediyorum."
  ],
  "Özgüven": [
    "Kendime inanıyorum.",
    "Yeterliyim, olduğum gibi değerliyim.",
    "Sesim önemli ve onu kullanmaktan çekinmiyorum.",
    "Kararlarımın arkasında duruyorum.",
    "Kendime güveniyorum ve sezgilerimi dinliyorum.",
    "Başkalarının onayına ihtiyacım yok.",
    "Güçlü yanlarımı biliyor ve kullanıyorum.",
    "Hatalarım bana öğretir, beni tanımlamaz.",
    "Kendimi dünkü halimle kıyaslıyorum, başkalarıyla değil.",
    "Korkularım var ama onlardan büyüğüm.",
    "Her gün biraz daha cesurum.",
    "Hayır demek benim hakkım.",
    "Kendimi ifade etmekten keyif alıyorum.",
    "Olduğum kişiden gurur duyuyorum.",
    "İçimde ihtiyacım olan gücü taşıyorum.",
    "Zorluklarla başa çıkabilirim.",
    "Kusurlarımla birlikte bütünüm.",
    "Kendi yolumu kendim çiziyorum.",
    "Yeni şeyler denemekten korkmuyorum.",
    "Fikirlerim değerli.",
    "Kendime verdiğim sözleri tutuyorum.",
    "Aynaya baktığımda gördüğüm kişiyi seviyorum.",
    "Benim ışığım kimseyle yarışmıyor.",
    "Hayatımın yazarı benim.",
    "Kendi değerimi başkalarının sözlerine bırakmıyorum.",
    "Zor anlarda bile kendime destek oluyorum.",
    "Kendimi küçültmeden var olabiliyorum.",
    "Başarabileceğime inanıyorum.",
    "İçimdeki eleştirmeni nazikçe susturuyorum.",
    "Kendim olmak benim süper gücüm.",
    "Korkuya rağmen adım atıyorum, cesaret budur.",
    "Kendimi affediyorum ve yoluma devam ediyorum.",
    "Düşüncelerimi açıkça söyleyebiliyorum.",
    "Benim gibi biri daha yok, bu harika.",
    "Hayatta yer kaplamaya hakkım var.",
    "Kendi kararlarımı vermekte özgürüm.",
    "Eleştiriyi büyümek için kullanıyorum.",
    "Kendimi her gün biraz daha iyi tanıyorum.",
    "İçimdeki çocuğa güven veriyorum.",
    "Sınırlarımı korumak kendime duyduğum saygıdır.",
    "Başkalarının ne düşündüğü beni durdurmuyor.",
    "Duruşum dik, bakışım net.",
    "Kendimi kanıtlamak zorunda değilim.",
    "Hata yapmaktan korkmadan deniyorum.",
    "Yeteneklerime güveniyorum.",
    "Her yeni gün kendime güvenimi artırıyor.",
    "Kendim için en iyisini istemekten çekinmiyorum.",
    "Zayıf anlarım da beni ben yapıyor.",
    "Kendi ritmimde ilerlemek bana yeter.",
    "İçimdeki güce dokunuyorum.",
    "Kendimle gurur duyacağım seçimler yapıyorum.",
    "Ben yeterliyim, her zaman da yeterliydim.",
    "Bugün kendime inanmak için bir sebep daha buluyorum."
  ],
  "Sağlık": [
    "Bedenim güçlü ve sağlıklı.",
    "Her nefesimle yenileniyorum.",
    "Bedenimi seviyor ve ona iyi bakıyorum.",
    "Bana iyi gelen yiyecekleri seçiyorum.",
    "Hücrelerim her gün kendini yeniliyor.",
    "Hareket etmek bana enerji veriyor.",
    "Uykum derin ve dinlendirici.",
    "Bedenimin sinyallerini dinliyorum.",
    "Su içmek bedenime gösterdiğim bir sevgi.",
    "Enerjim gün boyu dengeli.",
    "Dinlenmek de iyileşmenin bir parçası.",
    "Zihnim ve bedenim uyum içinde.",
    "Her gün biraz daha zindeyim.",
    "Bedenim kendini iyileştirmeyi biliyor.",
    "Sağlıklı alışkanlıklar benim için kolaylaşıyor.",
    "Yürüyüşlerim bana nefes aldırıyor.",
    "Stresi bedenimden nazikçe bırakıyorum.",
    "Bedenime teşekkür ediyorum.",
    "Kendime iyi bakmak benim önceliğim.",
    "Sağlığım en büyük hazinem.",
    "Bugün bedenim için güzel bir şey yapıyorum.",
    "Nefesim sakin ve derin.",
    "Bedenimi kıyaslamadan kabul ediyorum.",
    "Gücüm her gün artıyor.",
    "Esnek, hafif ve canlı hissediyorum.",
    "İyi beslenmek bana keyif veriyor.",
    "Bedenimin bilgeliğine güveniyorum.",
    "Ekrandan uzaklaşıp kendime dönüyorum.",
    "Gün ışığı bana iyi geliyor.",
    "Bedenimdeki gerginliği bırakıyorum.",
    "Sağlıklı bir hayatı hak ediyorum.",
    "Her adımım bedenime bir hediye.",
    "Sağlığımın sorumluluğunu sevgiyle alıyorum.",
    "Zihinsel sağlığıma da özen gösteriyorum.",
    "Ritmimi buluyor ve ona saygı duyuyorum.",
    "İyileşmek için sabırlıyım.",
    "Bedenimle barışığım.",
    "Her gün biraz daha güçleniyorum.",
    "Sabahları enerjiyle uyanıyorum.",
    "Bedenimi dinlemek beni güçlendiriyor.",
    "Sağlıklı seçimler yapmak bana doğal geliyor.",
    "Gülmek bedenime şifa veriyor.",
    "Kendime ayırdığım her dakika sağlığıma bir yatırım.",
    "Bedenim benim evim, ona özenle bakıyorum.",
    "Dengeli bir yaşam kuruyorum.",
    "Hareket etmeyi seviyorum.",
    "Sağlık ve canlılık benim doğal halim.",
    "Zihnimi de bedenim kadar besliyorum.",
    "Yorgunluğumu dinlenerek onarıyorum.",
    "Bedenim her gün benim için çalışıyor, ona minnettarım.",
    "İyi hissetmek benim hakkım.",
    "Sağlıklı alışkanlıklarım uzun ve mutlu bir hayat kuruyor.",
    "Bugün kendime şefkatle bakıyorum."
  ],
  "Huzur": [
    "Huzur içimde başlıyor.",
    "Sakin kalabilirim, nefesim benim çapam.",
    "Kontrol edemediklerimi bırakıyorum.",
    "Şu an, burada, güvendeyim.",
    "Zihnim berrak ve sakin.",
    "Her şeyin olması gerektiği gibi olduğuna güveniyorum.",
    "Acele etmeden yaşıyorum.",
    "Düşüncelerimi seçebilirim, bugün iyi olanı seçiyorum.",
    "Kaygılarımı nazikçe bırakıyorum.",
    "Yavaşlamak bana iyi geliyor.",
    "İç sesim yumuşak ve sakin.",
    "Huzuru küçük anlarda buluyorum.",
    "Geçmişi bırakıyor, şimdiye dönüyorum.",
    "Geleceği dert etmeden bugünü yaşıyorum.",
    "Kalbim hafif, zihnim dingin.",
    "Sessizlik bana güç veriyor.",
    "Her nefeste biraz daha gevşiyorum.",
    "Gerginliği bırakmak benim elimde.",
    "İçimdeki fırtına geçiyor, deniz duruluyor.",
    "Hayatın akışına teslim oluyorum.",
    "Kendime yavaşlama izni veriyorum.",
    "Etrafımda karmaşa olsa da içim sakin.",
    "Huzurlu bir ev, huzurlu bir zihin yaratıyorum.",
    "Bugün kendime nazik davranmayı seçiyorum.",
    "Dinlenmek de ilerlemenin bir parçası.",
    "Mükemmel olmak zorunda değilim.",
    "Her şeyi bir anda çözmem gerekmiyor.",
    "Güzel düşüncelerle uykuya dalıyorum.",
    "Kalbim dinginlikle dolu.",
    "Bırakmak beni özgürleştiriyor.",
    "Doğada huzurumu buluyorum.",
    "Endişe yerine güveni seçiyorum.",
    "Her sabaha sakin bir zihinle başlıyorum.",
    "Hayatımdaki karmaşayı sadeleştiriyorum.",
    "Barış önce içimde, sonra çevremde.",
    "Sorunlarımı sakin bir kafayla çözüyorum.",
    "Bana ağır gelenleri bırakıyorum.",
    "Huzurumu bozan şeylere sınır koyuyorum.",
    "Şimdiki an bana yetiyor.",
    "Nefesimi izliyorum, zihnim yavaşlıyor.",
    "Kendimle baş başa kalmaktan keyif alıyorum.",
    "İç huzurum dış koşullara bağlı değil.",
    "Bugün hiçbir şeyi zorlamıyorum.",
    "Ruhum dinleniyor.",
    "Her şey yolunda, ben de yolundayım.",
    "Kendi iç sesime güveniyorum.",
    "Zihnimi sevgiyle sakinleştiriyorum.",
    "Hafiflemeye kendime izin veriyorum.",
    "Akşamları günün yükünü bırakıyorum.",
    "Huzur benim doğal halim.",
    "Sükûnet içimde büyüyor.",
    "Bugün dingin ve dengedeyim.",
    "Yolumu kaybetsem de yıldızım beni bulur."
  ],
  "Başarı": [
    "Her küçük adım beni hedefime yaklaştırıyor.",
    "Başarı benim için mümkün ve yakın.",
    "Hayallerim planlarımla gerçekleşiyor.",
    "Hedeflerime odaklanıyorum.",
    "Disiplinim kendime verdiğim bir hediye.",
    "Bugün kendimle gurur duyacağım bir şey yapacağım.",
    "Zorluklar beni güçlendiriyor.",
    "Emeklerimin karşılığını alacağıma inanıyorum.",
    "Küçük alışkanlıklar büyük değişimler yaratır.",
    "Yeni başlangıçlar için hiçbir zaman geç değil.",
    "Fırsatlar beni buluyor, ben de hazırım.",
    "Her gün bir öncekinden daha iyiyim.",
    "Vazgeçmeden devam ediyorum.",
    "Başarıyı kendi tanımımla yaşıyorum.",
    "Odaklandığım şey büyüyor.",
    "Kararlılığım beni ileri taşıyor.",
    "Öğrenmeye ve gelişmeye açığım.",
    "Bugün merakla öğreniyorum.",
    "Planlarım bir bir gerçeğe dönüşüyor.",
    "Başarısızlık, başarıya giden yolun bir parçası.",
    "Yapabileceğimin en iyisini yapıyorum.",
    "Hedeflerim beni heyecanlandırıyor.",
    "Zamanımı akıllıca kullanıyorum.",
    "Her deneme beni biraz daha ustalaştırıyor.",
    "Başkalarının başarısı bana ilham veriyor.",
    "Yeteneklerimi dünyayla paylaşıyorum.",
    "Sabırla ve istikrarla ilerliyorum.",
    "Önümdeki engelleri birer basamağa çeviriyorum.",
    "Büyük hayaller kurmaya cesaretim var.",
    "İşimi tutkuyla yapıyorum.",
    "Bugün ertelemeden başlıyorum.",
    "Kendi potansiyelimin farkındayım.",
    "Başarı emeğimin doğal bir sonucu.",
    "Bitirdiğim her iş beni güçlendiriyor.",
    "Doğru insanlar ve fırsatlar yolumda.",
    "Hedefime giden yolu adım adım yürüyorum.",
    "Kendime koyduğum hedeflere ulaşıyorum.",
    "Çalışkanlığım meyvesini veriyor.",
    "Geri adım atsam da yolumdan dönmüyorum.",
    "Yaratıcılığım beni farklı kılıyor.",
    "Kariyerimde istediğim yere doğru ilerliyorum.",
    "Kazandığım her küçük zafer önemli.",
    "İlerlememi kutlamayı unutmuyorum.",
    "Yeni beceriler öğrenmek bana keyif veriyor.",
    "Bugün bir adım daha atıyorum.",
    "Hayallerimi ertelemiyorum.",
    "Başarıyı hak ediyorum.",
    "Hedeflerime kendi hızımda ulaşıyorum.",
    "Odak, sabır ve inançla ilerliyorum.",
    "Başlamak bitirmenin yarısıdır, başlıyorum.",
    "Her sabah hedeflerime yeniden bağlanıyorum.",
    "Yaptığım işle fark yaratıyorum.",
    "Gelecekteki ben, bugünkü emeğim için bana teşekkür edecek."
  ]
};
